### ISSUE TITLE
SMS/Messaging actions

### ISSUE THREAD

**Issue by abranson** [abranson/rockpool#10]
Expand Notification to include more than one action. There's a DBus method in ofono to send an SMS. Add page to edit the standard replies. Construct standard reply actions in SailfishPlatform.

**Comment by rufferson** [comment]
Linked to #37 - timeline engine makes actions flexible. will be implemented as part of timeline engine (see be33027b4 )

**Comment by rufferson** [comment]
I think this one could be closed as well now? We now cover even more than that
