### ISSUE TITLE
Installation of Rockpool on SailfishOS 4.5.0.16 fails

### ISSUE THREAD

**Issue by Fuzzillogic** [abranson/rockpool#107]
On upgrading to 4.5.0.16 the updater warned that Rockpool might conflict with this new version, so I uninstalled it prior updating. After updating, trying to install Rockpool 1.15 using Storeman fails. Same error (of course) as by using `pkcon`:

```
[root@XperiaXA2 defaultuser]# pkcon install rockpool
Resolving                                                                                                     
Testing changes                                                                                               
Finished                                                                                                     
Fatal error: nothing provides 'libquazip5.so.1' needed by the to be installed rockpool-1.15+sfos4.4.20230111102118.2.g69124a8-1.33.1.jolla.armv7hl
```

I don't know if this would be the only issue, but it is the first blocking one when trying to install.

**Comment by abranson** [comment]
> rockpool-1.15+sfos4.4.20230111102118.2.g69124a8-1.33.1.jolla.armv7hl

You're installing a version intended for 4.4. You can either build the master from here, or add the community OBS repo. But you'll need QtConnectivity which was removed from Sailfish but I've also built in my OBS.

**Comment by norayr** [comment]
please take a look at openrepos site, i complained there a lot, described what i did and it didn't work.
you can answer here, i discovered this thread late.

anyway, i edited the file which i got via, as recommended on openrepos:

```
ssu ar rockpool https://repo.sailfishos.org/obs/home:/abranson:/sailfishapps/armv7hl/
```

doing then 

```
zypper ref rockpool && zypper dup --from rockpool
```

results in `Nothing to do.` though rockpool is not installed.
rockpool can be installed by
```
zypper install rockpool
```

well that can only happen if i comment out what was written in the repo file, found it in `/etc/zypp/repos.d`, and write there

```
#[openrepos-abranson]
#name=openrepos-abranson
#failovermethod=priority
#type=rpm-md
#gpgcheck=0
#enabled=1
#baseurl=plugin:ssu?repo=openrepos-abranson
[home_abranson_sailfishapps]
name=Sailfish applications (armv7hl)
type=rpm-md
baseurl=https://repo.sailfishos.org/obs/home:/abranson:/sailfishapps/armv7hl/
enabled=1
```

still after that the rockpool is not able to detect the pebble classic i use.

**Comment by abranson** [comment]
I'm not sure what you've done here, but the openrepos-abranson repo is completely separate from my OBS repo, which should be added separately with the 'ssu ar' command. It's best to use ssu's config, as that will configure the zypp backend. Editing zypp config manually might go wrong.

If you're running an older version of SailishOS, such as on a community port, then the version on OBS probably wouldn't work as the dependencies will be wrong as you found with quazip.

**Comment by norayr** [comment]
oh thank you!

can you try to use the default openrepos config then?

with that, and the command on openrepos to install, i am not able to install the rockpool.

```
[root@XperiaXA2-DualSIM ~]# zypper ref rockpool && zypper dup --from rockpool
Repository 'rockpool' is up to date.
Specified repositories have been refreshed.
Loading repository data...
Reading installed packages...
Computing distribution upgrade...

Nothing to do.
```

can you double check if the repo works?

**Comment by abranson** [comment]
Ah I see the problem. I think when I wrote those instructions, I assumed people would already have a previous version installed, and so 'zypper dup', which just performs an upgrade, would work. You should use 'zypper in rockpool' I guess. You should remove the openrepos repository if you're using OBS. I don't think they'll clash, but it's possible.

**Comment by norayr** [comment]
thank you!

however...

i removed the OBS repo which i manually added and:

```
[root@XperiaXA2-DualSIM ~]# ssu rr rockpool
[root@XperiaXA2-DualSIM ~]# ssu ar rockpool https://repo.sailfishos.org/obs/home
:/abranson:/sailfishapps/armv7hl/
[root@XperiaXA2-DualSIM ~]# zypper ref rockpool && zypper in rockpool
Retrieving repository 'rockpool' metadata ................................[done]
Building repository 'rockpool' cache .....................................[done]
Specified repositories have been refreshed.
Building repository 'openrepos-Rikudou_Sennin' cache .....................[done]
Building repository 'openrepos-planetos_store' cache .....................[done]
Building repository 'openrepos-rob_k' cache ..............................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'libquazip5.so.1' needed by the to be installed rockpool-1.15+sfos4.4.20230111102118.2.g69124a8-1.33.1.jolla.armv7hl
 Solution 1: do not install rockpool-1.15+sfos4.4.20230111102118.2.g69124a8-1.33.1.jolla.armv7hl
 Solution 2: break rockpool-1.15+sfos4.4.20230111102118.2.g69124a8-1.33.1.jolla.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
```

as i understand this should not happen.

if i install from obs repo by having this config:

```
[home_abranson_sailfishapps]
name=Sailfish applications (armv7hl)
type=rpm-md
baseurl=https://repo.sailfishos.org/obs/home:/abranson:/sailfishapps/armv7hl/
enabled=1
```

then it installs fine, but is not able to see the peeble classic watch. even though the watch is paired. and it is not able to open bluetooth settings from the app.

**Comment by abranson** [comment]
Ok, I think you might be on an older version of sailfish then. The OBS is built against the latest.

Glad you got it installed anyway. Did you check the pairing for 'LE'? What's the name of the paired device?

**Comment by abranson** [comment]
That should just open the bluetooth page of the Settings app. What device name does the watch show on there? I think all the pebbles supported LE by the last firmware.

**Comment by abranson** [comment]
> Problem: nothing provides 'libquazip5.so.1' needed by the to be installed rockpool-1.15+sfos4.4.20230111102118.2.g69124a8-1.33.1.jolla.armv7hl

That version its picking up is the old one built for SFOS 4.4, from openrepos. So that explains what's going on there. You're better off sticking to OBS and removing the openrepos repository completely.

**Comment by norayr** [comment]
hello.
i tried to get back to this again.

so added the repo:

```
[root@XperiaXA2-DualSIM ~]# cat /etc/zypp/repos.d/ssu_openrepos-abranson_release
.repo
[openrepos-abranson]
name=openrepos-abranson
failovermethod=priority
type=rpm-md
gpgcheck=0
enabled=1
baseurl=plugin:ssu?repo=openrepos-abranson
[root@XperiaXA2-DualSIM ~]#
```

then trying to install:

```
[root@XperiaXA2-DualSIM repos.d]# zypper in rockpool

Building repository 'openrepos-Rikudou_Sennin' cache .....................[done]
Building repository 'openrepos-ade' cache ................................[done]
Building repository 'openrepos-fifr' cache ...............................[done]
Building repository 'openrepos-planetos_store' cache .....................[done]
Building repository 'openrepos-rob_k' cache ..............................[done]
Building repository 'rockpool' cache .....................................[done]
Building repository 'sailfishos-chum' cache ..............................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'libquazip5.so.1' needed by the to be installed rockpool-1.15+sfos4.4.20230111102118.2.g69124a8-1.33.1.jolla.armv7hl
 Solution 1: do not install rockpool-1.15+sfos4.4.20230111102118.2.g69124a8-1.33.1.jolla.armv7hl
 Solution 2: break rockpool-1.15+sfos4.4.20230111102118.2.g69124a8-1.33.1.jolla.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
```

os is the latest!

![Screenshot_20230925_001](https://github.com/abranson/rockpool/assets/11881650/0c6d7361-4fca-4337-9799-7441b2b0ba1b)

can you please check? may it be you are too sure that the repo is in perfect condition?

(again if i edit the repo file and add obs build, it will install and then fail to work, but you say it should install from openrepos!)

**Comment by norayr** [comment]
ok i made it work from the obs.

changed baseurl line to

```
https://repo.sailfishos.org/obs/home:/abranson:/sailfishapps/armv7hl/
```

then installed, by refreshing the cache.

it has some warnings after install

```
[root@XperiaXA2-DualSIM repos.d]# zypper in rockpool
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 2 NEW packages are going to be installed:
  qt5-qtwebsockets rockpool

2 new packages to install.
Overall download size: 1.2 MiB. Already cached: 0 B. After the operation,
additional 2.3 MiB will be used.
Continue? [y/n/v/...? shows all options] (y):
Retrieving package qt5-qtwebsockets-5.5.1+git1-1.7.1.jolla.armv7hl
                                           (1/2),  80.1 KiB ( 80.1 KiB unpacked)
Retrieving: qt5-qtwebsockets-5.5.1+git1-1.7.1.jolla.armv7hl.r[done (33.3 KiB/s)]
Retrieving package rockpool-1.15-1.36.1.jolla.armv7hl
                                           (2/2),   1.1 MiB (  2.2 MiB unpacked)
Retrieving: rockpool-1.15-1.36.1.jolla.armv7hl.rpm .........[done (149.3 KiB/s)]

Checking for file conflicts: .............................................[done]
(1/2) Installing: qt5-qtwebsockets-5.5.1+git1-1.7.1.jolla.armv7hl ........[done]
Additional rpm output:
warning: /home/.zypp-cache/packages/jolla/oss/armv7hl/qt5-qtwebsockets-5.5.1+git1-1.7.1.jolla.armv7hl.rpm: Header V3 RSA/SHA256 Signature, key ID 47394f23: NOKEY


(2/2) Installing: rockpool-1.15-1.36.1.jolla.armv7hl .....................[done]
Additional rpm output:
su: user nemo does not exist or the user entry does not contain all the required fields
su: user nemo does not exist or the user entry does not contain all the required fields
```

upon startup it was not able to recognize the paired watch but then i restarted the app and it started to see it.

so now it works, thank you.
