### ISSUE TITLE
App configuration doesn't work for some apps.

### ISSUE THREAD

**Issue by abranson** [abranson/rockpool#13]
JS apps in the daemon aren't completing initialization before the app config url is generated. Misfit inits a base_url variable in onReadyStateChanged, and this is currently empty when the config url is generated from it.

**Comment by raketti** [comment]
Is this also related to the issue that one cannot open a drop down menu in the App settings? When there's a drop down menu in the Watch face/App settings, it just gets selected, but cannot be opened and changed.

**Comment by abranson** [comment]
That should work in 0.7-2

**Comment by raketti** [comment]
I'll need to pick up a sim-adapter to get my Jolla going again, but I'll test it later and report.

**Comment by Uppis** [comment]
In 0.7-2 drop down menus work, but color picker only partly. You can select a color fo those what are visible in the box, but there's no way how to expose more colors !?

**Comment by raketti** [comment]
Might have been that I still had the older version running, updated to 0.7-2, killed daemon and restarted all - now the drop downs seems to work.

**Comment by rufferson** [comment]
color picker is purely JS generated, so this is a qtwebkit rendering bug. Maybe that's one of the reasons Jolla switched to QtMozEmbed from QtWebKit. However QtMozEmbed is not yet integrated into Silica API, so to use it we'd need to re-implement Sailfish-Browser in the GUI.

**Comment by rufferson** [comment]
Back to original issue: as far as I can tell - the ready callback fails because it's improperly called:
Here's ready definition
Pebble.addEventListener("ready", function (e) {
    "use strict";
    console.log("connect! " + e.ready);
    console.log(e.type);
...
However the JSmanager calls ready with no arguments:
    // We try to invoke the callbacks even if script parsing resulted in error...
    m_jspebble->invokeCallbacks("ready");
Hence it fails on the first line - console.log

**Comment by rufferson** [comment]
Committed a fix in 0b5b90c234 to my repo. Now misfit settings opening fine.

**Comment by abranson** [comment]
Thanks, bit of deja vu there. Michael must have missed this one: https://github.com/smokku/pebble/commit/643e5c21cf80e41d465637bab251e689d4980086

**Comment by rufferson** [comment]
Ha, indeed, identical :)
