### ISSUE TITLE
Re-order watch apps

### ISSUE THREAD

**Issue by abranson** [abranson/rockpool#14]
This is set from the phone now

**Comment by rufferson** [comment]
Why is it needed? There was this feature in the original GUI - meaning there's also support in the underlying API. I just don't get what is it for? Once i understand that I may return the reordering functionality using context menu f.i.

**Comment by abranson** [comment]
It sets the order that the apps appear in the menu of the watch. Lets you put your favourite apps at the top.

**Comment by rufferson** [comment]
So just to make it clear - this issue is for the missing feature in the GUI - to change apps order (will fix if yes) not for the missing DBus call (MoveApp that is)?

**Comment by abranson** [comment]
I think the DBus call is already there from RockWork: SetAppOrder. It gets called from Pebble::appsSorted.

**Comment by rufferson** [comment]
SetAppOrder yes, going to use that, however there's call MoveApp in rockwork/pebble.cpp which is missing in rockworkd/dbusinterface.cpp
Anyway it was rather rhetoric question to win some time till I add context menu options :)

**Comment by abranson** [comment]
Oh yeah, I see it! It's unimplemented in RockWork too.

**Comment by rufferson** [comment]
Fix committed, is it urgent to PR or can wait to stockpile some more?

**Comment by abranson** [comment]
Wow that's quick - I don't think anything's urgent now unless someone's watch breaks like the guy stuck on the recovery firmware. I just thought I'd collect a todo list in here. Please feel free to ad some issues if you spot stuff.
