### ISSUE TITLE
Bluetooth settings cannot be opened from the GUI

### ISSUE THREAD

**Issue by rufferson** [abranson/rockpool#15]
There are buttons in the GUI to open Bluetooth settings when Pebble is disconnected. Those buttons are still referencing to Ubuntu's settings://system/bluetooth scheme which doesn't work in Sailfish.
Potentially need to implement method suggested here - https://together.jolla.com/question/126841/question-how-to-start-qml-file-from-cli/ - however I cannot yet reach reliable results (eg. as it works from notification quick launcher).

**Comment by abranson** [comment]
Will have a poke to see how the quick settings shortcuts do it.

**Comment by rufferson** [comment]
Seems org.nemomobile.lipstick /LauncherModel org.nemomobile.lipstick.LauncherModel.notifyLaunching(string:"jolla-settings.desktop") followed by 
com.jolla.settings  /com/jolla/settings/ui com.jolla.settings.ui.showPage(string:"system_settings/connectivity/bluetooth") is sufficiently reliable when later is called in a callback to former's result handler.
Committed a fix where BT is called using QML DBus nemomobile plugin, will see how it goes.

**Comment by rufferson** [comment]
Tested multiple times from various places, looks stable.
