### ISSUE TITLE
Install apps / watchfaces from file is not working

### ISSUE THREAD

**Issue by AlphaX2** [abranson/rockpool#18]
In the developer tools menu is already an entry to "install app or watchface from file" but clicking on it has no reaction. No menu or option is opening.

**Comment by rufferson** [comment]
yes, known issue, working on it, all file picker features are currently not working.  That includes side import, screenshot share, send logs.

**Comment by rufferson** [comment]
Fixed in 64b19a753f

**Comment by rufferson** [comment]
P.S> Fixed only sideload, created separate file picker for it. Sharing picker (ContentPeer) is still missing in the Sailfish/Silica
