### ISSUE TITLE
No notifications except for call after update to 0.9.3

### ISSUE THREAD

**Issue by awlx** [abranson/rockpool#30]
Hi everybody,

since I updated my daemon including reboot of the phone. No notifications for SMS, Mail etc arrive at the clock anymore. 

Except for calls ...

Any hint what to do?

Cheers

**Comment by abranson** [comment]
What do you see on the 'manage notifications' page?

**Comment by awlx** [comment]
Sorry, my fault it seems that all notifications got disabled after upgrade. Going to enable all of them again.

**Comment by abranson** [comment]
It's a problem if everyone's defaulting to disabled notifications after the move to the new system. I'll have a look.

**Comment by abranson** [comment]
Yeah, the old values were true/false and the new were numbers, so everyone's coming out as 0 which is disabled. This might need a special hack. Thanks for the report.
