### ISSUE TITLE
Volume up doesn't work.

### ISSUE THREAD

**Issue by raketti** [abranson/rockpool#32]
Since updating to 0.9-4 (or maybe -3) the volume up control doesn't work. I can adjust the volume down from my Time Steel, but increasing the volume does nothing.

**Comment by raketti** [comment]
Restarted the daemon and now it seems to work. The update might have frozen the pulseaudio controls or similar (not a programmes, so just guessing). So if it isn't implemented yet, the daemon should be restarted after upgrade.

**Comment by abranson** [comment]
The daemon should be restarted during upgrade. I recently fixed a problem where the connection to the volume bus would be lost and neither of the volume controls would work, but I have no idea how only one of them would be broken!

I'll close this for now as it's working. Please re-open it if it happens again.
