### ISSUE TITLE
Situations App notifications no longer available in Rockpool since 0.10-1

### ISSUE THREAD

**Issue by raketti** [abranson/rockpool#34]
As the title says, there's no longer an entry for Situations in the notification settings of Rockpool since upgrading to 0.10-1.

I don't like to push the notifications to my Pebble, but I like to see them on the Events screen of my Jolla, but now I was forced to remove the notifications from Situations, because of a condition that changes the situation quite often when I'm on my yard (Wi-Fi coverage).

**Comment by abranson** [comment]
The situations notifications are a bit strange - there's owner set and there should be. I'll get it to use the sender if there's no owner, but that may have locale problems for those apps. There's nothing else to use for Situations - we should probably ask him to set the owner.

**Comment by raketti** [comment]
Thanks for the fix, I'll get back if the issue continues. I'll see if I can get through to the guy behind the Situations App.
