### ISSUE TITLE
Issue with integrated web browser

### ISSUE THREAD

**Issue by Tsht** [abranson/rockpool#41]
Browser can't set some settings (in this case : related to location).

Take for example the app : "BringMeHome".
https://apps.getpebble.com/en_US/application/555507e2f5c8ab916000002a?query=bringmehome&section=watchapps

After going to the parameters, you should set your location.
But the internal browser can't set either by "Current position" or either by using the google maps api (click is not responsive either by add current or add location in google api).

![screenshot-16-05-30-09-24-37](https://cloud.githubusercontent.com/assets/7195700/15642658/04ba0c88-2649-11e6-93f7-a1149591a3d5.png)

**Comment by rufferson** [comment]
most probably it tries to raise location dialog for which event handler is not implemented, let me check, need to extend gecko anyway for authentication.

**Comment by rufferson** [comment]
So with proposed fix it works (tested, nice app btw) - config page asks to name chosen location and hence attempts to raise prompt dialog.
You still need to enter location manually (eg address to the location details), need to figure out yet how to initialize properly geolocation provider. Don't want to enable it automatically and unconditionally as it may be abused.

**Comment by Tsht** [comment]
Oh, great :) I think it's ok to have it entered manually for most of the cases. Keep the really good work !
