### ISSUE TITLE
[ui] corners of square watchface overlap borders for Time Round

### ISSUE THREAD

**Issue by strixaluco** [abranson/rockpool#53]
As the title says, with a Time Round connected, the corners of square watchface overlap borders at the main Rockpool's window.

**Environment:**
Sailfish 2.0.4
Rockpool 1.2-1

**Screenshot:**
![time-round](https://cloud.githubusercontent.com/assets/10875796/20088082/c04307e0-a5b8-11e6-87f0-6284950e5962.png)

**Comment by rufferson** [comment]
this is weird, i have PTR and was actually (re)writing this GUI for PTR, which happened to be working for other platforms :)
Is it just for main screen or appstore also shows similar ugliness?

**Comment by strixaluco** [comment]
I assume you're talking about Pebble's appstore, right? Don't have PTR with me right now, but will try to check this by the end of the week.
Thanks.

**Comment by rufferson** [comment]
Yes, pebble appstore in the rockpool client - WatchApps -> (pull down) Add New -> (click on some app) App Details

**Comment by strixaluco** [comment]
Yes, thanks. Will try to check there as well.

**Comment by rufferson** [comment]
oh, i found. such a silliness, probably carried it out from original package. Will submit a fix now.

**Comment by strixaluco** [comment]
Cool :) That was fast!
