### ISSUE TITLE
Problem with nonLatin name of Caller in Incomming Call

### ISSUE THREAD

**Issue by vasvlad** [abranson/rockpool#57]
Pebble watch shows only "??????" in Incoming Call if name of caller includes nonLatin symbols (for Example in Russian language).

**Comment by abranson** [comment]
Is this with a Pebble Classic or Time? If it's a classic, did you install the language pack?

**Comment by vasvlad** [comment]
My Pebble is Peeble Classic
Yes, of course. My watch works fine with Android Mobile together.
Source of this problem https://github.com/abranson/rockpool/blob/master/rockworkd/libpebble/watchdatawriter.cpp String #34. Function writePascalString is not tolerant to UTF-8. :)

**Comment by abranson** [comment]
Hmm, I thought only the Pebble Times supported UTF-8, which is why the classics need the language packs. Do you get this problem for other text as well, or is it only for calls?

**Comment by vasvlad** [comment]
Problem is only for calls. Another messages show correctly.
Function writePascalString calls only for  PhoneCallEndpoint::phoneControl and TimeMessage::serialize() functions.

**Comment by abranson** [comment]
Ok thanks very much for the info, I'll look further into this and your fix. I need to know it won't mess things up for the Time watches, and I also wonder why it didn't come up in issue #26

**Comment by vasvlad** [comment]
I've read issue #26 
I know about problem with fonts in screenshot. This is problem in language pack. My problem has "???" in text instead Cyrillic symbols.

**Comment by rufferson** [comment]
Did you capture it from android or how did you come to this way of packing? WritePascalString is what libpebble2 does for IncomingCall action. Of course it could also be flawed and in real app different packing being used, just wonder where did you get that format from.
