### ISSUE TITLE
Jolla crashe, related to rockpool and a specific app

### ISSUE THREAD

**Issue by Tsht** [abranson/rockpool#59]
Hello.
With the last and last version only of Weathergraph watchface, on my jolla C and on my Pebble watch steel, 
1 - rockpool service seems to loop restart
2 - my jolla phone crashes and reboot :(
I'm pretty sure it's Rockpool which makes my phone crash, because when I select another watchface it won't do it anymore.

If I can look at some logs I can do it.

**Comment by abranson** [comment]
Sorry to hear that. Some journal logs from around the crash would be great. journalctl -flab as root should do it.

**Comment by abranson** [comment]
I installed this on my old Pebble Classic and on my brand new Pebble Time Steel but it seems fine. Have you been able to get it to happen again?

**Comment by Tsht** [comment]
Hello.
Can't reproduce it. Sorry to have made you test. May be related with some server connection issues from the app (I noted once I had to wait for some weather update or location searching, with the app trying to update data very very frequently).
If I can reproduce it I will use journalctl -flab. 
Thank you very much. Please tell me if I have to close this issue :)

**Comment by abranson** [comment]
No problem, since I wrote this I found out that ruff added some much better logging you can turn on in Developer Tools>Report Problems. You can create a rockpool specific log file in /tmp, which is much easier than the journal.
