### ISSUE TITLE
Initialize pebble

### ISSUE THREAD

**Issue by storma** [abranson/rockpool#6]
After a factory reset, you can pair you pebble but when opening Rockpool and selecting your pebble, you are left with "Your Pebble smartwatch is in factory mode and needs to be initialized."

Pressing the "Initialize Pebble" does nothing.

**Comment by abranson** [comment]
That button should open the firmware upgrade page, but that isn't done yet. In the meantime, you can use dbus for the moment, or wait for the page the be migrated. I'll leave this open until it's done.

**Comment by abranson** [comment]
Should work now!
