### ISSUE TITLE
Document project's license

### ISSUE THREAD

**Issue by FlorentRevest** [abranson/rockpool#71]
Hi,

I would be interested in re-using some of the code of rockpool for my own GPL-licensed SFOS app. However, I can't find any clear indications of rockpool's license.

Could you please add a LICENSE file and use standard license headers in the source code of rockpool and rockpoold? This way, I can make sure I'll properly credit the rockpool's developers.

Thank you for this project

**Comment by abranson** [comment]
Hi,

I asked the same question of Rockwork, which this was forked from, and they pointed me to the License field in the spec file, which gives GPLv3. I thought I should keep things the same for Rockpool. Glad you like the project, and I'm very much looking forward to seeing what you plan to do with it...

**Comment by FlorentRevest** [comment]
Thanks for the quick answer! This is good to know.
