### ISSUE TITLE
Update to Rebble

### ISSUE THREAD

**Issue by alan-morford** [abranson/rockpool#75]
Ubuntu Touch pebble app RockWork has been updated to work with Rebble servers. It'd be great to see RockPool updated too since it's store access is now broken.

**Comment by abranson** [comment]
Do you have a link? I checked here: https://bazaar.launchpad.net/~mzanetti/rockwork/trunk/changes and that looks like it hasn't been updated in over a year.

**Comment by alan-morford** [comment]
https://github.com/bhdouglass/rockwork

**Comment by alan-morford** [comment]
Thanks!  Does the package have to be built and uploaded to openrepos before it shows in Storeman or does a process pull the change and auto-package?

**Comment by abranson** [comment]
i'll have to upload it to openrepos for it to show there, but I want to review the other Pebble pieces before I do that. Rockpool supports a lot more of that stuff that Rockwork did. I'd also like to get the translations updated, but the guy who has the access details to that isn't responding.

**Comment by abranson** [comment]
Btw, if you want a package now, you'll find it on the Mer OBS

**Comment by alan-morford** [comment]
I'll pull down the package off the repository tonight and help you test. I'll let you know.  Happy to help you test anything else too.  We worked together a while ago on the service restart pull down option via the comments on openrepos if you remember.

**Comment by alan-morford** [comment]
Installed the package from Mer OBS and all is well. Thanks.

**Comment by norayr** [comment]
I found rockpool 1.7 [here](http://repo.merproject.org/obs/home:/abranson:/sailfishapps/armv7hl/armv7hl/rockpool-1.7-1.16.2.jolla.armv7hl.rpm), installed it, and when i try to login, it goes to pebble.com again, not to rebble.

did i download the right file? how do i force it to work with rebble repositories?

**Comment by norayr** [comment]
wow, but watchfaces now are installable!

**Comment by raketti** [comment]
https://github.com/abranson/rockpool/blob/ad124f5f78f328a32fbe1ffa47cf32ae9d84fd42/rockwork/qml/pages/SettingsPage.qml#L131

Needs to be changed to direct to Rebble login.
