### ISSUE TITLE
Sailfish 4 - Rockpoold 1.11: Undefined Symbol

### ISSUE THREAD

**Issue by Tiggez** [abranson/rockpool#96]
After the major release Sailfish 4.x rockpoold does not start.

The error message is: rockpoold: symbol loockup error: rockpoold: undefined symbol_ _Z5mkCal16ExtendedCalendarC1ERKN9KDateTime4SpecE

Thank you for your great work.

Tiggez

**Comment by abranson** [comment]
1.12 is updated for Sailfish 4.1. I guess I should have targetted 4.0 too.

**Comment by Tiggez** [comment]
Just got the update from openrepo.

You sir are one of my personal heros ;)

Thanks and stay safe

Am Donnerstag, 27. Mai 2021 schrieb Andrew Branson:
> 1.12 is updated for Sailfish 4.1. I guess I should have targetted 4.0 too.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/abranson/rockpool/issues/96#issuecomment-84951806

-- 
Gesendet von meinem Jolla
